### ISSUE TITLE
DevContainer: SyntaxError: Unexpected token '', ""... is not valid JSON

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#2774]
### What happened?

I get this error message running the PRQL Dev Container with Docker 4.20.1 on macOS 12.6.3 with the current commit 90077ed. This particular output comes from an earlier commit 90649f8, but the error message is identical as far as I can see.

The error message might have a "NUL" character between the single quotes, and multiple NULs between the double quotes. Here's the snippet near the error:

```
[174232 ms] Start: Run in container: cat '/home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/product.json'
[174244 ms] SyntaxError: Unexpected token '', ""... is not valid JSON
```

Here's the tail of the Dev Container output from VS Code. What other troubleshooting information could I provide? Thanks.

```
...
[174047 ms] Start: Run in container: /bin/sh
[174051 ms] userEnvProbe: loginInteractiveShell (default)
[174051 ms] Start: Run in container: test -f '/tmp/devcontainers-017e830e-541a-4de2-9729-d95afc69563a1686309016601/env-loginInteractiveShell.json'
[174052 ms] Start: Run in container: echo ~
[174053 ms] /Users/richb/.gnupg
[174053 ms] 
[174054 ms] 
[174054 ms] 
[174054 ms] Exit code 1
[174055 ms] Start: Run in container: gpgconf --list-dir homedir
[174055 ms] userEnvProbe: not found in cache
[174055 ms] userEnvProbe shell: /bin/bash
[174059 ms] /home/vscode/.gnupg
[174059 ms] 
[174059 ms] Start: Run in container: # Test for /home/vscode/.ssh/known_hosts and ssh
[174066 ms] 
[174067 ms] 
[174067 ms] Start: Run in container: # Test for /home/vscode/.gnupg/pubring.gpg and gpg
[174072 ms] 
[174072 ms] 
[174072 ms] Start: Run in container: # Copy /Users/richb/.ssh/known_hosts to /home/vscode/.ssh/known_hosts
[174095 ms] 
[174095 ms] 
[174095 ms] Start: Run in container: # Copy /Users/richb/.gnupg/pubring.gpg to /home/vscode/.gnupg/pubring.gpg
[174119 ms] 
[174119 ms] 
[174120 ms] Start: Run in container: # Test for /home/vscode/.gnupg/trustdb.gpg and gpg
[174134 ms] 
[174134 ms] 
[174134 ms] Start: Run in container: # Copy /Users/richb/.gnupg/trustdb.gpg to /home/vscode/.gnupg/trustdb.gpg
[174141 ms] 
[174141 ms] 
[174142 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[174146 ms] 
[174146 ms] 
[174146 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/node /tmp/vscode-remote-containers-dfb2f3a9-3c70-416c-be0b-282f68585d50.js git-credential-helper $*; }; f' || true
[174155 ms] 
[174155 ms] 
[174155 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[174215 ms] /home/vscode
[174215 ms] 
[174215 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-dfb2f3a9-3c70-416c-be0b-282f68585d50.js' >/tmp/vscode-remote-containers-dfb2f3a9-3c70-416c-be0b-282f68585d50.js
[174219 ms] 
[174219 ms] 
[174220 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-dfb2f3a9-3c70-416c-be0b-282f68585d50.js' >/tmp/vscode-remote-containers-server-dfb2f3a9-3c70-416c-be0b-282f68585d50.js_1686309191973
[174232 ms] Start: Run in container: cat '/home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/product.json'
[174244 ms] SyntaxError: Unexpected token '', ""... is not valid JSON
        at JSON.parse (<anonymous>)
        at n6 (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:224:1268)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async t6 (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:220:733)
        at async vm (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:194:9112)
        at async Wbe (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:288:7491)
        at async DK (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:288:6424)
        at async BO (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:279:4972)
[174245 ms] 
[174245 ms] 
[174252 ms] Container server: /bin/sh: 32: /home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/node: Exec format error
[174266 ms] Error: stream ended with:0 but wanted:9
        at c (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:24:101670)
        at /Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:24:101851
        at s (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:27:5371)
        at Socket.<anonymous> (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/extension/extension.js:27:5541)
        at Socket.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1358:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[174267 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-017e830e-541a-4de2-9729-d95afc69563a1686309016601' && cat > '/tmp/devcontainers-017e830e-541a-4de2-9729-d95afc69563a1686309016601/env-loginInteractiveShell.json' << 'envJSON'
[174267 ms] Container server terminated (code: 126, signal: null).
[174270 ms] 
[174270 ms] 
```

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### MVCE confirmation

- [ ] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thanks for the complete issue!

Does anyone know where the `product.json` is coming from? It looks like it's maybe nothing to do with us; `/home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/product.json`? But it seems unlikely all devcontainers are broken...

We discussed having tests for this at https://github.com/PRQL/prql/pull/2635#discussion_r1210969061. @eitsupi did you happen to have any thoughts on that? As well finding any bugs, it would also let us quickly discriminate between an issue of PRQL's vs. something with a specific setup... But not sure they're possible without a whole VSCode setup in CI??

**Comment by max-sixty** [comment]
FWIW it does work on my end. So it might be worth clearing `/home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/product.json` and trying again, but no guarantees.

**Comment by richb-hanover** [comment]
Update: It's working now. I didn't know where to find `/home/vscode/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/product.json`

So I just used Docker Desktop to delete all containers, images, and volumes (even for projects that could not be related) and re-started the Dev Container. I realize that's pretty draconian, but those other items are easily rebuilt when I get around to running them again.

It took a while to rebuild, but that seems to have solved the problem - I can now `task run-website` etc.

**Comment by richb-hanover** [comment]
**Update:** I need to say that I was not "being gentle" to the Dev Container. Prior to this problem, I realized that I wanted to try an earlier commit, so I simply quit from VS Code while it was starting up the Dev Container.

Could that have corrupted something? Is there a better way to abort/stop a Dev Container? Thanks.

**Comment by eitsupi** [comment]
@richb-hanover I think your issue is nothing to do with PRQL, but related to the Dev Container VS Code extension.
So please check this repository. https://github.com/microsoft/vscode-remote-release

I think the VSCode in the container was broken for some reason.

**Comment by eitsupi** [comment]
> I realized that I wanted to try an earlier commit, so I simply quit from VS Code while it was starting up the Dev Container.

Immediately after the container is created, VSCode installs VSCode Server in the container. Perhaps the server was broken as a result of a forced termination during the download process.

**Comment by eitsupi** [comment]
In general, if a container is broken, simply rebuild the container.

**Comment by richb-hanover** [comment]
@eitsupi I figured as much, but I think the container was in some kind of bad state. VS Code offered to rebuild the container, but it always led to the same error message. That's why I used Docker Desktop to remove all the containers, images, and volumes.
