### ISSUE TITLE
Dev Container: An error occurred setting up the container

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#2794]
### What happened?

﻿﻿Using c4bcc62f on my Intel MacBook Pro (12.6.3). I got the following error message.

I used Docker Desktop to delete all containers, images, and volumes. Then I pulled c4bcc62f, and opened VS Code. It retrieved all the images and after a reasonable amount of time gave this message.

NB: I frequently get this message when starting a new dev container. But pressing Retry usually allows it to proceed. (Or quitting VS Code and re-launching lets it continue.)

In this case, "Retry" restarts the Dev Container, but leads to the same error. What other troubleshooting info can I provide? Thanks.

<img width="266" alt="image" src="https://github.com/PRQL/prql/assets/1094930/6aeb25e8-f003-43ee-a28f-4d57c14ac555">

```
[61 ms] Dev Containers 0.295.0 in VS Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302).
[60 ms] Start: Resolving Remote
[94 ms] Setting up container for folder or workspace: /Users/richb/github/prql
[95 ms] Context: desktop-linux
[96 ms] Start: Check Docker is running
[97 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[163 ms] Server API version: 1.43
[163 ms] Start: Run: docker volume ls -q
[220 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/richb/github/prql --filter label=vsch.quality=stable
[277 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/richb/github/prql --filter label=devcontainer.config_file=/Users/richb/github/prql/.devcontainer/devcontainer.json
[335 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/richb/github/prql
[391 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/richb/github/prql
[449 ms] Start: Run: /Applications/Tools-Developer/VSCode-osx/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/richb/github/prql --id-label devcontainer.local_folder=/Users/richb/github/prql --id-label devcontainer.config_file=/Users/richb/github/prql/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/richb/github/prql/.devcontainer/devcontainer.json --mount-workspace-git-root true
[688 ms] @devcontainers/cli 0.42.0. Node.js v16.17.1. darwin 21.6.0 x64.
[688 ms] Start: Run: git rev-parse --show-cdup
[700 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/richb/github/prql --filter label=devcontainer.config_file=/Users/richb/github/prql/.devcontainer/devcontainer.json
[764 ms] Start: Run: /Applications/Tools-Developer/VSCode-osx/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/richb/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-096fcd32-980b-4156-a22f-55cf8fe629e51686486143988 --workspace-folder /Users/richb/github/prql --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/richb/github/prql --id-label devcontainer.config_file=/Users/richb/github/prql/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/richb/github/prql/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1020 ms] @devcontainers/cli 0.42.0. Node.js v16.17.1. darwin 21.6.0 x64.
[1020 ms] Start: Run: docker buildx version
[1301 ms] github.com/docker/buildx v0.10.5 86bdced7766639d56baa4c7c449a4f6468490f87
[1302 ms] 
[1302 ms] Start: Resolving Remote
[1304 ms] Start: Run: git rev-parse --show-cdup
[1314 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/richb/github/prql --filter label=devcontainer.config_file=/Users/richb/github/prql/.devcontainer/devcontainer.json
[1371 ms] Start: Run: docker inspect --type image ghcr.io/prql/prql-devcontainer-base:latest
[1430 ms] local container features stored at: /Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/node_modules/vscode-dev-containers/container-features
[1431 ms] Start: Run: tar --no-same-owner -x -f -
[1446 ms] * Processing feature: ghcr.io/devcontainers/features/hugo:1
[1555 ms] Start: Run: docker-credential-desktop get
[2082 ms] * Processing feature: ghcr.io/devcontainers/features/python:1
[2211 ms] * Processing feature: ghcr.io/devcontainers/features/node:1
[2362 ms] * Processing feature: ghcr.io/eitsupi/devcontainer-features/go-task:1
[2510 ms] * Fetching feature: hugo_1_oci
[2691 ms] * Fetching feature: python_2_oci
[2913 ms] * Fetching feature: node_3_oci
[3102 ms] * Fetching feature: go-task_4_oci
[3289 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/t7/txh6j62h8xjfkd0059b7m_k00000gn/T/devcontainercli/container-features/0.42.0-1686486146088 --build-arg _DEV_CONTAINERS_BASE_IMAGE=ghcr.io/prql/prql-devcontainer-base:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-prql-9f40321c918454ef5606d0b253dbf67515a9f27786c98684dc77956402624bf4-features -f /var/folders/t7/txh6j62h8xjfkd0059b7m_k00000gn/T/devcontainercli/container-features/0.42.0-1686486146088/Dockerfile.extended /Users/richb/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[+] Building 0.0s (2/2) FINISHED                                                
 => ERROR [internal] load build definition from Dockerfile.extended        0.0s
 => [internal] load .dockerignore                                          0.0s
------
 > [internal] load build definition from Dockerfile.extended:
------
ERROR: failed to solve: failed to read dockerfile: failed to create lease: read-only file system
[3545 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/t7/txh6j62h8xjfkd0059b7m_k00000gn/T/devcontainercli/container-features/0.42.0-1686486146088 --build-arg _DEV_CONTAINERS_BASE_IMAGE=ghcr.io/prql/prql-devcontainer-base:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-prql-9f40321c918454ef5606d0b253dbf67515a9f27786c98684dc77956402624bf4-features -f /var/folders/t7/txh6j62h8xjfkd0059b7m_k00000gn/T/devcontainercli/container-features/0.42.0-1686486146088/Dockerfile.extended /Users/richb/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[3545 ms]     at mte (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3286)
[3545 ms]     at IN (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3222)
[3545 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[3545 ms]     at async Ote (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:3660)
[3546 ms]     at async Hf (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:4775)
[3546 ms]     at async Qre (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10371)
[3546 ms]     at async Zre (/Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10112)
[3553 ms] Exit code 1
[3555 ms] Command failed: /Applications/Tools-Developer/VSCode-osx/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/richb/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/richb/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-096fcd32-980b-4156-a22f-55cf8fe629e51686486143988 --workspace-folder /Users/richb/github/prql --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/richb/github/prql --id-label devcontainer.config_file=/Users/richb/github/prql/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/richb/github/prql/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[3555 ms] Exit code 1
```

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### MVCE confirmation

- [ ] Minimal example
- [X] New issue

**Comment by eitsupi** [comment]
From the error message, I suspect that the error may be unrelated to this repository.
I recommend taking a look at this repository. https://github.com/microsoft/vscode-remote-release

**Comment by max-sixty** [comment]
Any chance this is out of the disk space which docker allocates itself, given the disk error? Does `docker system prune --all` help? (it'll remove all images tbc)

(agree it's probably not a PRQL issue, but happy to try and help...)

**Comment by richb-hanover** [comment]
Thanks - I don't know how the dev container got in a bad state, but its working now. I did `docker system prune --all` and also deleted my copy of the repo followed by `git clone ...`.

I'll keep better track of what seems to be wrong if this ever happens again. Thanks.
